version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=somepassword
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/quiz-show
    ports:
      - "8001:8001"
    depends_on:
      - db